version: '3.3'

services:
  nginx:
    container_name: local-node
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: "Asia/Shanghai"
    restart: always
    ports:
      - "8200:80"
    volumes:
      - .:/var/www/oa_project_front
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
